apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: tools
  source:
    path: apps/cert-manager-crds
    repoURL: https://github.com/atoy3731/k8s-tools-app.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true