apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: tools
  source:
    path: apps/rancher
    repoURL: https://github.com/atoy3731/k8s-tools-app.git
    targetRevision: master
    helm:
      values: |
        hostname: "rancher.demo.atoy.dev"
        rancherImageTag: "v2.4.8"
        ingress:
          tls:
            source: letsEncrypt
        letsEncrypt:
          email: adam@atoy.dev
          environment: staging
          ingress:
            class: "traefik"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
