apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-impl
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: tools
  source:
    path: apps/vault-impl
    repoURL: https://github.com/atoy3731/k8s-tools-app.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true